/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS_TVertex extends TopoDS_TShape {
  private transient long swigCPtr;

  protected TopoDS_TVertex(long cPtr, boolean cMemoryOwn) {
    super(TopoDSJNI.TopoDS_TVertex_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopoDS_TVertex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TopoDSJNI.delete_TopoDS_TVertex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TopAbs_ShapeEnum ShapeType() {
    return TopAbs_ShapeEnum.swigToEnum(TopoDSJNI.TopoDS_TVertex_ShapeType(swigCPtr, this));
  }

}
