/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS {
  public static void process_exception(SWIGTYPE_p_Standard_Failure error, SWIGTYPE_p_std__string method_name, SWIGTYPE_p_std__string class_name) {
    TopoDSJNI.process_exception(SWIGTYPE_p_Standard_Failure.getCPtr(error), SWIGTYPE_p_std__string.getCPtr(method_name), SWIGTYPE_p_std__string.getCPtr(class_name));
  }

}
