/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS_Shape {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TopoDS_Shape(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopoDS_Shape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TopoDSJNI.delete_TopoDS_Shape(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TopoDS_Shape(TopoDS_Shape arg0) {
    this(TopoDSJNI.new_TopoDS_Shape__SWIG_0(TopoDS_Shape.getCPtr(arg0), arg0), true);
  }

  public boolean Checked() {
    return TopoDSJNI.TopoDS_Shape_Checked__SWIG_0(swigCPtr, this);
  }

  public void Checked(boolean theIsChecked) {
    TopoDSJNI.TopoDS_Shape_Checked__SWIG_1(swigCPtr, this, theIsChecked);
  }

  public boolean Closed() {
    return TopoDSJNI.TopoDS_Shape_Closed__SWIG_0(swigCPtr, this);
  }

  public void Closed(boolean theIsClosed) {
    TopoDSJNI.TopoDS_Shape_Closed__SWIG_1(swigCPtr, this, theIsClosed);
  }

  public void Complement() {
    TopoDSJNI.TopoDS_Shape_Complement(swigCPtr, this);
  }

  public TopoDS_Shape Complemented() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_Complemented(swigCPtr, this), true);
  }

  public void Compose(TopAbs_Orientation theOrient) {
    TopoDSJNI.TopoDS_Shape_Compose(swigCPtr, this, theOrient.swigValue());
  }

  public TopoDS_Shape Composed(TopAbs_Orientation theOrient) {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_Composed(swigCPtr, this, theOrient.swigValue()), true);
  }

  public boolean Convex() {
    return TopoDSJNI.TopoDS_Shape_Convex__SWIG_0(swigCPtr, this);
  }

  public void Convex(boolean theIsConvex) {
    TopoDSJNI.TopoDS_Shape_Convex__SWIG_1(swigCPtr, this, theIsConvex);
  }

  public SWIGTYPE_p_std__string DumpJsonToString(int depth) {
    return new SWIGTYPE_p_std__string(TopoDSJNI.TopoDS_Shape_DumpJsonToString__SWIG_0(swigCPtr, this, depth), true);
  }

  public SWIGTYPE_p_std__string DumpJsonToString() {
    return new SWIGTYPE_p_std__string(TopoDSJNI.TopoDS_Shape_DumpJsonToString__SWIG_1(swigCPtr, this), true);
  }

  public TopoDS_Shape EmptyCopied() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_EmptyCopied(swigCPtr, this), true);
  }

  public void EmptyCopy() {
    TopoDSJNI.TopoDS_Shape_EmptyCopy(swigCPtr, this);
  }

  public boolean Free() {
    return TopoDSJNI.TopoDS_Shape_Free__SWIG_0(swigCPtr, this);
  }

  public void Free(boolean theIsFree) {
    TopoDSJNI.TopoDS_Shape_Free__SWIG_1(swigCPtr, this, theIsFree);
  }

  public int HashCode(int theUpperBound) {
    return TopoDSJNI.TopoDS_Shape_HashCode(swigCPtr, this, theUpperBound);
  }

  public int __hash__() {
    return TopoDSJNI.TopoDS_Shape___hash__(swigCPtr, this);
  }

  public boolean Infinite() {
    return TopoDSJNI.TopoDS_Shape_Infinite__SWIG_0(swigCPtr, this);
  }

  public void Infinite(boolean theIsInfinite) {
    TopoDSJNI.TopoDS_Shape_Infinite__SWIG_1(swigCPtr, this, theIsInfinite);
  }

  public boolean IsEqual(TopoDS_Shape theOther) {
    return TopoDSJNI.TopoDS_Shape_IsEqual(swigCPtr, this, TopoDS_Shape.getCPtr(theOther), theOther);
  }

  public boolean IsNotEqual(TopoDS_Shape theOther) {
    return TopoDSJNI.TopoDS_Shape_IsNotEqual(swigCPtr, this, TopoDS_Shape.getCPtr(theOther), theOther);
  }

  public boolean IsNull() {
    return TopoDSJNI.TopoDS_Shape_IsNull(swigCPtr, this);
  }

  public boolean IsPartner(TopoDS_Shape theOther) {
    return TopoDSJNI.TopoDS_Shape_IsPartner(swigCPtr, this, TopoDS_Shape.getCPtr(theOther), theOther);
  }

  public boolean IsSame(TopoDS_Shape theOther) {
    return TopoDSJNI.TopoDS_Shape_IsSame(swigCPtr, this, TopoDS_Shape.getCPtr(theOther), theOther);
  }

  public TopoDS_Shape Located(TopLoc_Location theLoc) {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_Located(swigCPtr, this, TopLoc_Location.getCPtr(theLoc), theLoc), true);
  }

  public TopLoc_Location Location() {
    return new TopLoc_Location(TopoDSJNI.TopoDS_Shape_Location__SWIG_0(swigCPtr, this), false);
  }

  public void Location(TopLoc_Location theLoc) {
    TopoDSJNI.TopoDS_Shape_Location__SWIG_1(swigCPtr, this, TopLoc_Location.getCPtr(theLoc), theLoc);
  }

  public boolean Locked() {
    return TopoDSJNI.TopoDS_Shape_Locked__SWIG_0(swigCPtr, this);
  }

  public void Locked(boolean theIsLocked) {
    TopoDSJNI.TopoDS_Shape_Locked__SWIG_1(swigCPtr, this, theIsLocked);
  }

  public boolean Modified() {
    return TopoDSJNI.TopoDS_Shape_Modified__SWIG_0(swigCPtr, this);
  }

  public void Modified(boolean theIsModified) {
    TopoDSJNI.TopoDS_Shape_Modified__SWIG_1(swigCPtr, this, theIsModified);
  }

  public void Move(TopLoc_Location thePosition) {
    TopoDSJNI.TopoDS_Shape_Move(swigCPtr, this, TopLoc_Location.getCPtr(thePosition), thePosition);
  }

  public TopoDS_Shape Moved(TopLoc_Location thePosition) {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_Moved(swigCPtr, this, TopLoc_Location.getCPtr(thePosition), thePosition), true);
  }

  public int NbChildren() {
    return TopoDSJNI.TopoDS_Shape_NbChildren(swigCPtr, this);
  }

  public void Nullify() {
    TopoDSJNI.TopoDS_Shape_Nullify(swigCPtr, this);
  }

  public boolean Orientable() {
    return TopoDSJNI.TopoDS_Shape_Orientable__SWIG_0(swigCPtr, this);
  }

  public void Orientable(boolean theIsOrientable) {
    TopoDSJNI.TopoDS_Shape_Orientable__SWIG_1(swigCPtr, this, theIsOrientable);
  }

  public TopAbs_Orientation Orientation() {
    return TopAbs_Orientation.swigToEnum(TopoDSJNI.TopoDS_Shape_Orientation__SWIG_0(swigCPtr, this));
  }

  public void Orientation(TopAbs_Orientation theOrient) {
    TopoDSJNI.TopoDS_Shape_Orientation__SWIG_1(swigCPtr, this, theOrient.swigValue());
  }

  public TopoDS_Shape Oriented(TopAbs_Orientation theOrient) {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_Oriented(swigCPtr, this, theOrient.swigValue()), true);
  }

  public void Reverse() {
    TopoDSJNI.TopoDS_Shape_Reverse(swigCPtr, this);
  }

  public TopoDS_Shape Reversed() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Shape_Reversed(swigCPtr, this), true);
  }

  public TopAbs_ShapeEnum ShapeType() {
    return TopAbs_ShapeEnum.swigToEnum(TopoDSJNI.TopoDS_Shape_ShapeType(swigCPtr, this));
  }

  public SWIGTYPE_p_opencascade__handleT_TopoDS_TShape_t TShape() {
    return new SWIGTYPE_p_opencascade__handleT_TopoDS_TShape_t(TopoDSJNI.TopoDS_Shape_TShape__SWIG_0(swigCPtr, this), true);
  }

  public void TShape(SWIGTYPE_p_opencascade__handleT_TopoDS_TShape_t theTShape) {
    TopoDSJNI.TopoDS_Shape_TShape__SWIG_1(swigCPtr, this, SWIGTYPE_p_opencascade__handleT_TopoDS_TShape_t.getCPtr(theTShape));
  }

  public TopoDS_Shape() {
    this(TopoDSJNI.new_TopoDS_Shape__SWIG_1(), true);
  }

  public boolean __eq_wrapper__(TopoDS_Shape other) {
    return TopoDSJNI.TopoDS_Shape___eq_wrapper__(swigCPtr, this, TopoDS_Shape.getCPtr(other), other);
  }

}
