/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS_Vertex extends TopoDS_Shape {
  private transient long swigCPtr;

  protected TopoDS_Vertex(long cPtr, boolean cMemoryOwn) {
    super(TopoDSJNI.TopoDS_Vertex_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopoDS_Vertex obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TopoDSJNI.delete_TopoDS_Vertex(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TopoDS_Vertex(TopoDS_Vertex arg0) {
    this(TopoDSJNI.new_TopoDS_Vertex__SWIG_0(TopoDS_Vertex.getCPtr(arg0), arg0), true);
  }

  public TopoDS_Vertex() {
    this(TopoDSJNI.new_TopoDS_Vertex__SWIG_1(), true);
  }

}
