/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS_AlertWithShape {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TopoDS_AlertWithShape(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopoDS_AlertWithShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TopoDSJNI.delete_TopoDS_AlertWithShape(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public TopoDS_Shape GetShape() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_AlertWithShape_GetShape(swigCPtr, this), true);
  }

  public boolean Merge(SWIGTYPE_p_opencascade__handleT_Message_Alert_t theTarget) {
    return TopoDSJNI.TopoDS_AlertWithShape_Merge(swigCPtr, this, SWIGTYPE_p_opencascade__handleT_Message_Alert_t.getCPtr(theTarget));
  }

  public void SetShape(TopoDS_Shape theShape) {
    TopoDSJNI.TopoDS_AlertWithShape_SetShape(swigCPtr, this, TopoDS_Shape.getCPtr(theShape), theShape);
  }

  public boolean SupportsMerge() {
    return TopoDSJNI.TopoDS_AlertWithShape_SupportsMerge(swigCPtr, this);
  }

  public TopoDS_AlertWithShape(TopoDS_Shape theShape) {
    this(TopoDSJNI.new_TopoDS_AlertWithShape(TopoDS_Shape.getCPtr(theShape), theShape), true);
  }

}
