/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS_Iterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected TopoDS_Iterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopoDS_Iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TopoDSJNI.delete_TopoDS_Iterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Initialize(TopoDS_Shape S, boolean cumOri, boolean cumLoc) {
    TopoDSJNI.TopoDS_Iterator_Initialize(swigCPtr, this, TopoDS_Shape.getCPtr(S), S, cumOri, cumLoc);
  }

  public boolean More() {
    return TopoDSJNI.TopoDS_Iterator_More(swigCPtr, this);
  }

  public void Next() {
    TopoDSJNI.TopoDS_Iterator_Next(swigCPtr, this);
  }

  public TopoDS_Iterator() {
    this(TopoDSJNI.new_TopoDS_Iterator__SWIG_0(), true);
  }

  public TopoDS_Iterator(TopoDS_Shape S, boolean cumOri, boolean cumLoc) {
    this(TopoDSJNI.new_TopoDS_Iterator__SWIG_1(TopoDS_Shape.getCPtr(S), S, cumOri, cumLoc), true);
  }

  public TopoDS_Shape Value() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_Iterator_Value(swigCPtr, this), true);
  }

}
