/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TopoDS_HShape extends Standard_Transient {
  private transient long swigCPtr;

  protected TopoDS_HShape(long cPtr, boolean cMemoryOwn) {
    super(TopoDSJNI.TopoDS_HShape_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TopoDS_HShape obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        TopoDSJNI.delete_TopoDS_HShape(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TopoDS_Shape ChangeShape() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_HShape_ChangeShape(swigCPtr, this), true);
  }

  public void Shape(TopoDS_Shape aShape) {
    TopoDSJNI.TopoDS_HShape_Shape__SWIG_0(swigCPtr, this, TopoDS_Shape.getCPtr(aShape), aShape);
  }

  public TopoDS_Shape Shape() {
    return new TopoDS_Shape(TopoDSJNI.TopoDS_HShape_Shape__SWIG_1(swigCPtr, this), true);
  }

  public TopoDS_HShape() {
    this(TopoDSJNI.new_TopoDS_HShape__SWIG_0(), true);
  }

  public TopoDS_HShape(TopoDS_Shape aShape) {
    this(TopoDSJNI.new_TopoDS_HShape__SWIG_1(TopoDS_Shape.getCPtr(aShape), aShape), true);
  }

}
